### ISSUE TITLE
Problem of installation in production

### ISSUE THREAD

**Issue by cdisabatino** [discendum/salava#26]
Hello. I can not make the Salava project work. I followed the procedure, but then I can not access the application through the Firefox browser. Can this application be deployed for production?
Thanking you,
Christophe

**Comment by cdisabatino** [comment]
I managed to install the application but there are still errors.
My question is still relevant: can this application be deployed in production ?

Thank you

**Comment by Isaakay111** [comment]
Yes, we currently have it deployed in production @[Open Badge Passport](https://openbadgepassport.com)

**Comment by cdisabatino** [comment]
Hello,
Okay. Thank you for the response and all the work done on the project.
