### ISSUE TITLE
Warning on Figwheel, cljsbuild and scss compiler

### ISSUE THREAD

**Issue by cdisabatino** [discendum/salava#29]
Hello,
When I execute the "lein develop" command, I have the warnings below.
Should not modfier dependencies to correct warnings?

Thanks,
Christophe

> WARNING: pos-int? already refers to: #'clojure.core/pos-int? in namespace: taoensso.encore, being replaced by: #'taoensso.encore/pos-int?
WARNING: bytes? already refers to: #'clojure.core/bytes? in namespace: taoensso.encore, being replaced by: #'taoensso.encore/bytes?
WARNING: pos-int? already refers to: cljs.core/pos-int? being replaced by: taoensso.encore/pos-int? at line 235 target/generated/public/js/out/taoensso/encore.cljs

**Comment by Isaakay111** [comment]
These do not affect functionality, we will correct those in due time. You are anyway welcome to fix those and make a pull request.
