### ISSUE TITLE
List of country names is not up to date

### ISSUE THREAD

**Issue by milikicn** [discendum/salava#4]
When registering, a user is asked to choose a country. But the list is not up to date. Interestingly, I noticed this as my country (Serbia) is not listed here, but only Yugoslavia (dissolved in 2006).

I would suggest updating this list in _salava.core.countries_ maybe from [this source](http://help.surveymonkey.com/articles/en_US/kb/Do-you-have-a-list-of-countries) (I suppose the list is up to date as the last officially recognized country "South Sudan" in 2011 is here on the list).

**Comment by ajk** [comment]
Fixed in 0d5eae780c20
