### ISSUE TITLE
README should be updated regarding configuring test_config/core.edn

### ISSUE THREAD

**Issue by milikicn** [discendum/salava#6]
Since test related config is now read from the file at _resources/test_config/core.edn_ (as per commit [7ce02a0c43d7d57474875b6d15c29e16702df9c5](https://github.com/discendum/salava/commit/7ce02a0c43d7d57474875b6d15c29e16702df9c5)), README should be updated about that stating that this file needs to be created and configured. Without creating this file, code will not compile as there will be an error at namespace _salava.core.migrator_ (file migrator.clj:11:18).

**Comment by ajk** [comment]
Looks like changes happen too fast for docs to keep up :) 
I added a line about test config to README.
