### ISSUE TITLE
Connecting OBF to Salava

### ISSUE THREAD

**Issue by Wardormeur** [discendum/salava#8]
Hi there :)
First of all, thanks for your work !
We're looking into connecting OBP to OBF, but it seems I can't find the right combination of parameters.
The factory plugin is activated in core.edn, endpoints are answering properly and displayed in swagger.
The OBF connectivity test seems to fail no matter what i set. It's also strange that the connectivity test doesn't send the salava_uri in the payload.
What are the expected parameters for the connectivity tests?
Based on what's described, that'd what i expected to input
Base url : http(s)://myobpurl/ (should I specify /obpv1/ ?)
OBF API endpoint url: https://openbadgefactory.com/v1/
API key : obf_api (default)
API secret: 123456 (default)
Cheers and thanks !

**Comment by ajk** [comment]
Hello,

The Salava API config in Open Badge Factory should look like this:

Base URL
- your Salava installation url, e.g. https://your.domain.name

OBF API endpoint URL
- the factory plugin route in your installation, e.g. https://your.domain.name/app/obpv1/factory

API key and API secret
- same as the values in your Salava config

I'm currently writing new deployment instructions so the process should be better covered soon :)

**Comment by Wardormeur** [comment]
Thanks @ajk, I'll give it another try next week :)

**Comment by Wardormeur** [comment]
Connectivty works, thanks !
For anyone interested, the call made by "Test connection" is a /POST to yourdomain/obpv1/factory/backpack_email_list with AuthBasic set from your your factory.edn conf with the following payload : `{
    "emails": [
        "salava.test@example.com"
    ]
}`
